services:
  rspamd:
    build:
      context: "."
      dockerfile: "Dockerfile.rspamd"
    container_name: rspamd-compose-rspamd
    depends_on:
      - knot
      - redis
    environment:
      - RSPAMD_DNS_SERVERS=round-robin:192.0.2.254:53
      - RSPAMD_REDIS_SERVERS=rspamd-compose-redis
      - RSPAMD_USE_BAYES=1
#      - RSPAMD_USE_GREYLIST=1
    networks:
      - rspamd
    ports:
      - "127.0.0.1:11332:11332"
      - "127.0.0.1:11333:11333"
      - "127.0.0.1:11334:11334"
    pull_policy: build
# recommended for production
#    read_only: true
    volumes:
      - rspamd-compose-rspamd-dbdir:/var/lib/rspamd

  redis:
    container_name: rspamd-compose-redis
    command: "redis-server --save 60 1 --loglevel warning"
    image: "redis:latest"
    networks:
      - rspamd
    volumes:
      - rspamd-compose-redis-data:/data

  knot:
    build:
      context: "."
      dockerfile: "Dockerfile.knot"
    container_name: rspamd-compose-knot
    command: "-n -c /etc/knot-resolver/kresd.conf"
    networks:
      rspamd:
        ipv4_address: 192.0.2.254
    pull_policy: build
    volumes:
      - rspamd-compose-knot-data:/data


networks:
  rspamd:
    ipam:
      config:
        - subnet: 192.0.2.0/24


volumes:
  rspamd-compose-knot-data:
  rspamd-compose-redis-data:
  rspamd-compose-rspamd-dbdir:
